Select * From PURCHLINE

Select * From PURCHTABLE

Select  B.ITEMID,
		B.NAMEALIAS,
		B.PRODUCT,
		B.BOMUNITID,
		B.CREATEDDATETIME,
		B.CREATEDBY,
		B.MODIFIEDDATETIME,
		B.AXXWHTAXGROUP,
		C.DISPLAYPRODUCTNUMBER,
		D.NAME,
		D.PARTITION,
		D.RECID

from INVENTTABLE B

join [dbo].[ECORESPRODUCT]C
	On B.PRODUCT = C.RECID
	
join ECORESPRODUCTTRANSLATION D
	On C.RECID = D.PRODUCT

--Where D.RECID = 5637221958
--where d.NAME like '%REPARACION TURBO%'