
USE OPERACIONES
SELECT TOP 3 * FROM [OPERACIONES].[RrHh].[AccionAcc]
SELECT TOP 3 * FROM [RrHh].[CtrolMedico]
SELECT TOP 3 * FROM [RrHh].[CuerpoAcc]
SELECT TOP 3 * FROM [RrHh].[CtrolMedico]
SELECT TOP 3 * FROM [RrHh].[DIAGNOSTICO]
SELECT TOP 3 * FROM [RrHh].[ESPECIALIDAD]
SELECT TOP 3 * FROM [RrHh].[LesionAcc]
SELECT TOP 3 * FROM [RrHh].[LugarAtencion]
SELECT TOP 3 * FROM [RrHh].[Medicamento]
SELECT TOP 3 * FROM [RrHh].[MedicinaLab_Ate]
SELECT TOP 3 * FROM [RrHh].[MedicinaLab_Cab]
SELECT TOP 3 * FROM [RrHh].[Medicos]
SELECT TOP 3 * FROM [RrHh].[RESULTADOCTROL]
SELECT TOP 3 * FROM [RrHh].[SUBESPECIALIDAD]
SELECT TOP 3 * FROM [RrHh].[TipoAtencion]
SELECT TOP 3 * FROM [RrHh].[TipoLugarAtencion]
SELECT TOP 3 * FROM [RrHh].[TRASLADOS]
SELECT TOP 3 * FROM [RrHh].[VISITASMEDICAS]
SELECT TOP 3 * FROM [Samel].[FueraDeProc]
SELECT TOP 3 * FROM [Samel].[RegFueraDeProc]
SELECT TOP 3 * FROM [Samel].[RegFueraDeProc]
