select * from ITCAXPROD.INFORMATION_SCHEMA.COLUMNS where COLUMN_NAME like 'RECVERSION' 


select A.TABLE_NAME, A.COLUMN_NAME, A.DATA_TYPE, A.CHARACTER_MAXIMUM_LENGTH  from ITCAXPROD.INFORMATION_SCHEMA.COLUMNS A where COLUMN_NAME like 'ACCOUNTID' 



select *, A.TABLE_NAME, A.COLUMN_NAME, A.DATA_TYPE, A.CHARACTER_MAXIMUM_LENGTH  from ITCAXPROD.INFORMATION_SCHEMA.COLUMNS A where COLUMN_NAME like 'ACCOUNTNUM' 


select *  from ITCAXPROD.INFORMATION_SCHEMA.COLUMNS A where COLUMN_NAME like 'NAME' 