SELECT CAST (132 AS DECIMAL(5,2))
SELECT CAST (PI() AS FLOAT)

USE OPERACIONES
GO
CREATE TABLE TABLA1(
	Id INT IDENTITY,
	Description VARCHAR(1000)
)


INSERT INTO TABLA1 (Description) VALUES ('HOLA CUELO')

SELECT * FROM TABLA1

SELECT Description FROM TABLA1

SELECT COUNT(*) FROM TABLA1

UPDATE TABLA1 SET Description = 'Hello, CUELO' WHERE Id = 2

DELETE FROM TABLA1 WHERE Id=1

