Select * from [dbo].[ECORESPRODUCT]

Select A.DISPLAYPRODUCTNUMBER,A.SEARCHNAME from [dbo].[ECORESPRODUCT] A

Select B.PRODUCT,C.* , D.* from INVENTTABLE B
join [dbo].[ECORESPRODUCT]C
On B.PRODUCT = C.RECID
join ECORESPRODUCTTRANSLATION D
On C.RECID = D.PRODUCT
where d.NAME like '%REPARACION TURBO%'



Select * from [dbo].[ECORESPRODUCT]


Select * from [dbo].[ECORESPRODUCTTRANSLATION]

