SELECT        TOP (100) PERCENT dbo.SERVICIOTRANSPORTE.STR_FECHA AS FECHA, 
						dbo.SERVICIOTRANSPORTE.STR_TIPOVHC AS [TIPO VHC], 
						dbo.SERVICIOTRANSPORTE.STR_ESTADO AS ESTADO, 
                        dbo.SERVICIOTRANSPORTE.STR_NROVALE AS [NRO VALE], 
						dbo.SERVICIOTRANSPORTE.STR_VALORVIAJE, 
						dbo.SERVICIOTRANSPORTE.STR_ESPERA_IMP, 
						dbo.SERVICIOTRANSPORTE.STR_PRECIO AS PRECIO, 
                        dbo.SERVICIOTRANSPORTE.STR_NECVALE AS [NEC VALE], 
						dbo.SERVICIOTRANSPORTE.STR_VALEINT AS [VALE INT], 
						dbo.V_TOTPASAJEROS.CANT AS CANTIDAD, 
						dbo.PASAJEROREMIS.PSJ_LEGAJO AS LEGAJO, 
                        dbo.PASAJEROREMIS.PSJ_APELLIDOYNOMBRE AS [APELLIDO Y NOMBRE], 
						ROUND(dbo.SERVICIOTRANSPORTE.STR_PRECIO / dbo.V_TOTPASAJEROS.CANT, 2) AS [PRECIO X PAX], 
                        dbo.PASAJEROREMIS.PSJ_GCIA AS GERENCIA, 
						dbo.PASAJEROREMIS.PSJ_ORGANISMO AS ORGANISMO, 
						dbo.SERVICIOTRANSPORTE.STR_BASE AS BASE, 
						dbo.EMPLEADO.EMP_SUCURSAL AS SUCURSAL, 
                        dbo.SERVICIOTRANSPORTE.STR_EMPRESA AS EMPRESA, 
						
						CASE WHEN RTRIM(dbo.PASAJEROREMIS.PSJ_AUTORIZACION) = '' 
							THEN 'CABECERA' 
							ELSE dbo.PASAJEROREMIS.PSJ_AUTORIZACION 
						END AS AUTORIZACION, 
                        
						dbo.SERVICIOTRANSPORTE.STR_HORASAL AS [HORA SAL], 
						dbo.SERVICIOTRANSPORTE.STR_HORALLE AS [HORA LLE], 
						dbo.SERVICIOTRANSPORTE.STR_TIPO AS TIPO, 
						dbo.SERVICIOTRANSPORTE.Id_Destino, 
                        Transporte.Destinos.Destino, 
						dbo.SERVICIOTRANSPORTE.STR_RECORRIDO AS Recorrido, 
						dbo.VEHICULODOC.DVE_INTERNO, 
						dbo.EMPLEADO.EMP_CIUDAD, dbo.EMPLEADO.EMP_DIRECCION


FROM            dbo.V_TOTPASAJEROS 
				INNER JOIN dbo.SERVICIOTRANSPORTE 
						ON dbo.V_TOTPASAJEROS.PSJ_ID = dbo.SERVICIOTRANSPORTE.STR_ID 
				
				INNER JOIN dbo.PASAJEROREMIS 
						ON dbo.SERVICIOTRANSPORTE.STR_ID = dbo.PASAJEROREMIS.PSJ_ID 
				
				INNER JOIN Transporte.Destinos 
						ON dbo.SERVICIOTRANSPORTE.Id_Destino = Transporte.Destinos.Id_Destino 
				
				LEFT OUTER JOIN dbo.VEHICULODOC 
						ON dbo.SERVICIOTRANSPORTE.DVE_ID = dbo.VEHICULODOC.DVE_ID 
				
				LEFT OUTER JOIN dbo.EMPLEADO 
						ON dbo.PASAJEROREMIS.PSJ_LEGAJO = dbo.EMPLEADO.EMP_LEGAJO 
				
				LEFT OUTER JOIN  dbo.PASAJEROEXT 
						ON dbo.PASAJEROREMIS.PSJ_LEGAJO = dbo.PASAJEROEXT.PSE_ID



WHERE        (dbo.SERVICIOTRANSPORTE.STR_ESTADO = 'CUMPLIDO')



/* Tabla PSAJEROSREMIS */
select * from dbo.V_TOTPASAJEROS

select top 100 * from dbo.PASAJEROREMIS order by PSJ_LEGAJO




/* Tabla dbo.SERVICIOTRANSPORTE */
SELECT * FROM dbo.SERVICIOTRANSPORTE




/* Transporte.Destinos  */
select Top 100 * from Transporte.Destinos 





/***********************************************/
select * from dbo.VEHICULODOC



/*--------------------------------------------*/
select * from dbo.PASAJEROEXT
select * from dbo.PASAJEROREMIS order by PSJ_ID desc



select * from 






