USE [DW]
GO

/****** Object:  Table [dbo].[MOD_CertificacionItemDatos]    Script Date: 18/12/2020 17:49:53 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[F_GESTIONRAMPA](
	[IdGestionRampa] [bigint] IDENTITY(1,1) NOT NULL,
	[IdCertificacionItemsDatos] [bigint] NULL,
	[CodigoCertificacionItemsDatos] [bigint] NULL,
	[IdCertificacionItem] [bigint] NULL,
	[IdCertificacion] [bigint] NULL,
	[IdEstadoCertificacion] [int] NULL,
	[IdCia] [int] NULL,
	[IdAeropuerto] [int] NULL,
	[IdTipoCbte] [int] NULL,
	[NroCertificacion] [bigint] NULL,
	[Id_Firmante] [int] NULL,
	[TipoLiq] [int] NULL,
	[IdAeronave] [int] NULL,
	[IdMatricula] [int] NULL,
	[NroVuelo] [int] NULL,
	[FechaLlegada] [date] NULL,
	[HoraProgramadaLlegada] [varchar](5) NULL,
	[IdIataAeropuertoSalida] [int] NULL,
	[IdTipoVuelo] [int] NULL,
	[IdEstadoVuelo] [int] NULL,
	[CodigoPlanificacionVuelos] [bigint] NULL,
	[IdVueloSalida] [bigint] NULL,
	[IdOperacionItems] [bigint] NULL,
	[IdOperacion] [bigint] NULL,
	[IdEstadoOperacionItems] [int] NULL,
	[IdTarea] [int] NULL,
	[Cantidad] [decimal](10, 2) NULL,
	[Id_Reversa] [bigint] NULL,
	[Cancelado] [bit] NULL,
	[Ajustado] [bit] NULL,
	[NumeroOrden] [int] NULL,
	[Desde] [datetime] NULL,
	[Hasta] [datetime] NULL,
	[Momento] [datetime] NULL,
	[IdTipoServicio] [int] NULL,
	[IdProgramacionVuelos] [bigint] NULL,
	[IdTipoMovimiento] [int] NULL,
	[FechaCertificacion] [Date] NULL,
	[TiempoProgramado] [datetime] NULL,
	[TiempoReal] [datetime] NULL,
	[HoraReal] [varchar](5) NULL,
	[FechaReal] [Date] NULL,
	[TiempoInicioDespacho] [datetime] NULL,
	[TiempoInicioDespachoCarga] [datetime] NULL,
	[IdPosicion] [int] NULL,
	[MovimientoCarga] [bit] NULL,
	[InformaCarga] [bit] NULL,
	[KgCarga] [decimal](10, 2) NULL,
	[AperturaBodega] [datetime] NULL,
	[CierreBodega] [datetime] NULL,
	[HoraInicio] [datetime] NULL,
	[HoraLiberado] [datetime] NULL,
	[IdRelacionCategoriaDemora] [int] NULL,
	[PrimerEquipaje] [datetime] NULL,
	[UltimoEquipaje] [datetime] NULL,
	[UbicLat] [numeric](11, 8) NULL,
	[UbicLong] [numeric](11, 8) NULL,
	[IdTipoDemora] [int] NULL,
	[Programado] [bit] NULL,
	[AperturaBodega_Calzado_min] [int] NULL,
	[CintaInicio_Calzado_min] [int] NULL,
	[CintaFin_Calzado_min] [int] NULL,
	[PasarelaTelescopica_Calzado_min] [int] NULL,
	[PasarelaTelescopica_b] [bit] NULL,
	[Escalera_Calzado_min] [int] NULL,
	[Bus_b] [bit] NULL,
	[GPU_min] [int] NULL,
	[AireAcondicionado_min] [int] NULL,
	[HuboLimpieza_b] [bit] NULL,
	[TieneFirma_b] [bit] NULL,
	[IdFirmante] [int] NOT NULL,
	[UsuarioPortal] [varchar](50) NOT NULL,
	[FirmaPortal_b] [bit] NULL,
	[CertificacionesConAjuste] [int] NULL,
	[Id_CertificacionLiq] [int] NOT NULL,
	[CodigoCertificacionLiqObs] [int] NOT NULL,
	[Observacion] [varchar](max) NOT NULL,
	[FecUltAct] [datetime] NULL,
	[UsuUltAct] [varchar](50) NULL

	)


