/****** Script for SelectTopNRows command from SSMS  ******/
SELECT  [IdDemoras]
      ,[CodigoReal]
      ,[Fecha]
      ,[GrupoAtencionLLegada]
      ,[HorarioProgramadoLlegada]
      ,[Aeronave]
      ,[FechaLlegada]
      ,[HorarioRealLlegada]
      ,[HorarioEstimadoLlegada]
      ,[GrupoAtencionSalida]
      ,[HorarioProgramadoSalida]
      ,[FechaSalida]
      ,[HorarioRealSalida]
      ,[CodObservacion]
      ,[DetalleObservacion]
      ,[HorarioEstimadoSalida]
      ,[CodCliente]
      ,[NombreCliente]
      ,[Estado]
      ,[MotivoCancelado]
      ,[TipoServicio]
      ,[TipoVuelo]
      ,[Escala]
      ,[MotivoDemora]
      ,[CausaDemora]
      ,[CodMotivoDemora]
      ,[CodCausaDemora]
      ,[ObservacionDemora]
      ,[MotivoCausaDemora]
      ,[Demorado]
      ,[FecUltAct]
      ,[UsuUltAct]
  FROM [DW].[dbo].[F_DEMORAS]